"""Runtime configuration, loaded from environment (Cloud Run --set-env-vars / .env)."""
import os


def _b(name, default):
    return os.environ.get(name, default)


PROJECT_ID = _b("PROJECT_ID", "")
PROJECT_NUMBER = _b("PROJECT_NUMBER", "")
LOCATION = _b("LOCATION", "global")               # global | us | eu
DATA_STORE_ID = _b("DATA_STORE_ID", "ge-search-demo")

# security trimmer
# IDENTITY_SOURCE decides WHOSE identity filters the data (RBAC). This is NOT the same as
# who can reach the site — that's the IAP allow-list (terraform var.iap_members).
#   demo = trust the persona switcher header (X-Demo-User), so a visitor can explore as any
#          seeded persona (David/Nick/Ravi). DEMOS ONLY — the client picks the identity, so
#          it must never gate real/sensitive data.
#   iap  = trust the IAP-signed header (X-Goog-Authenticated-User-Email): the real signed-in
#          user filters THEIR OWN data via their Firestore group_users. The persona switcher
#          / X-Demo-User / ?u= are ignored. Use this for any real deployment.
IDENTITY_SOURCE = _b("IDENTITY_SOURCE", "demo")    # demo | iap
FIRESTORE_DATABASE = _b("FIRESTORE_DATABASE", "(default)") or "(default)"  # literal "(default)"

# answer generation
# All answers are generated by the Gemini Enterprise engine assistant (:streamAssist) — see
# ASSISTANT_ID / ASSISTANT_PATH below. Querying the GE engine keeps generation covered by the
# GE per-seat subscription. There is no client-selectable model or alternate engine.

# retrieval tuning
PAGE_SIZE = int(_b("PAGE_SIZE", "10"))
OVERFETCH = int(_b("OVERFETCH", "5"))              # retrieve PAGE_SIZE*OVERFETCH, then trim
FACET_SAMPLE = int(_b("FACET_SAMPLE", "100"))     # breadth for computing dynamic facets
# Optional recency boost — OFF by default. On this demo corpus (~all docs 2023-2026) a
# blanket year boost adds no signal and actively corrupts the engine's native relevance
# ranking: verified live that "amgen pipeline highlights" ranks correctly (Amgen clinical
# papers first) natively, but a +0.3 boost on 2024-26 promotes weaker recent off-topic
# papers above them. Set e.g. "2025,2026" only for a corpus with a wide date range where
# recency is a genuine tie-breaker. "" disables.
BOOST_RECENT_YEARS = _b("BOOST_RECENT_YEARS", "")

# Semantic re-ranking via the Discovery Engine Ranking API, applied to the ACL-trimmed
# results BEFORE the AI summary/answer — so both the shown results and what Gemini grounds
# on are ordered by a cross-encoder reranker. Best-effort: a failure/unavailable model is a
# no-op (native ranking stands). Overfetch RERANK_TOP_N, rerank, then show PAGE_SIZE.
# NOTE: the standalone Ranking API (rankingConfigs:rank) is a separately-billed Vertex AI Search
# call (NOT routed through the GE engine), so it's OFF by default to keep all traffic covered by
# the GE subscription. The GE engine's :search already returns well-ranked results. Turn on only
# if you accept the separate ranking charge.
RERANK = _b("RERANK", "off").lower() == "on"
RERANK_MODEL = _b("RERANK_MODEL", "") or "semantic-ranker-default@latest"
RERANK_TOP_N = int(_b("RERANK_TOP_N", "50"))
# Request extractive segments from VAIS and feed them (not the short snippet) to the reranker
# and grounding prompt — snippets are keyword fragments and score low on the cross-encoder.
RERANK_EXTRACTIVE = _b("RERANK_EXTRACTIVE", "on").lower() == "on"

# --- GE assistant (:streamAssist) options ------------------------------------------
# Pin the generation model for the assistant (generationSpec.modelId). Empty = the GE
# engine's default (recommended — the engine picks a covered model). Set only if you need
# a specific model and have confirmed it's available + subscription-covered for your tier.
ASSIST_MODEL_ID = _b("ASSIST_MODEL_ID", "")
# userMetadata sent with each assist call so date-relative ("this quarter") and localized
# answers are correct. TIME_ZONE is an IANA name (e.g. "America/Los_Angeles"); LANGUAGE is
# a BCP-47 code (e.g. "en"). Empty = omit that field.
ASSIST_TIME_ZONE = _b("ASSIST_TIME_ZONE", "")
ASSIST_LANGUAGE = _b("ASSIST_LANGUAGE", "")
# Inject inline [n] citation markers into the answer text from the assistant's
# citationMetadata (offsets → the same numbered Sources list). off = Sources list only.
ASSIST_INLINE_CITATIONS = _b("ASSIST_INLINE_CITATIONS", "on").lower() == "on"
# Search-as-you-type autocomplete via the engine completionConfig:completeQuery.
AUTOCOMPLETE = _b("AUTOCOMPLETE", "on").lower() == "on"

# BigQuery logging (searches + feedback)
BQ_LOGGING = _b("BQ_LOGGING", "on")               # on | off
BQ_DATASET = _b("BQ_DATASET", "ge_search_logs")


DE_HOST = ("discoveryengine.googleapis.com" if LOCATION == "global"
           else f"{LOCATION}-discoveryengine.googleapis.com")
DATA_STORE_PATH = (f"projects/{PROJECT_ID}/locations/{LOCATION}/collections/"
                   f"default_collection/dataStores/{DATA_STORE_ID}")
# Enterprise features (Answer API, extractive answers/segments) are NOT available on a
# standard-edition data store and must be queried via the ENGINE (app) serving config. When
# ENGINE_ID is set we point :search/:answer at the engine; otherwise we fall back to the
# data-store serving config (standard edition / data-store-only — no extractive/Answer API).
# Document fetch + user events stay on DATA_STORE_PATH (they're data-store-scoped).
ENGINE_ID = _b("ENGINE_ID", "")
ENGINE_PATH = (f"projects/{PROJECT_ID}/locations/{LOCATION}/collections/"
               f"default_collection/engines/{ENGINE_ID}")
SERVING_CONFIG = (f"{ENGINE_PATH}/servingConfigs/default_search" if ENGINE_ID
                  else f"{DATA_STORE_PATH}/servingConfigs/default_search")
# GE assistant used for grounded answers (:streamAssist). Queried on the GE engine so the call
# is covered by the GE subscription (same reason :search must hit the engine, not the data store).
ASSISTANT_ID = _b("ASSISTANT_ID", "default_assistant")
ASSISTANT_PATH = f"{ENGINE_PATH}/assistants/{ASSISTANT_ID}"
SIGNED_URL_MINUTES = int(_b("SIGNED_URL_MINUTES", "30"))
