import { ArrowLeft } from "lucide-react";
import { Wordmark } from "./Logo";

const SECTIONS: { src?: string; title: string; body: string }[] = [
  {
    src: "/diagrams/arch-search.svg",
    title: "Core search — ACL-safe, query-time, GE-engine",
    body: "Every query is trimmed to what the signed-in user may see. Search runs against the Gemini Enterprise engine's serving config (not the data store directly), filtered on an indexed acl_groups field (the user's live Firestore groups); facets cascade, and a page-level Firestore re-check is the safety net. Routing through the GE engine means search traffic is covered by the GE per-seat subscription. The AI answer is opt-in and grounded only on the trimmed set.",
  },
  {
    src: "/diagrams/arch-ai.svg",
    title: "AI answers — Gemini Enterprise engine, subscription-covered",
    body: "AI is opt-in (search stays fast and LLM-free by default), and every answer grounds only on documents the user may see. Answers are generated by the Gemini Enterprise engine assistant (:streamAssist) — query understanding, retrieval, grounded generation, and inline citations, all server-side — scoped by the same server-enforced acl_groups (+ facet) filter the search trim uses, so the ACL trim holds. The same path powers the result-set answer, follow-up Q&A, and per-document Q&A (steered to the document by title). Because all calls (search + answer) go through the GE engine, they draw on the pooled per-seat subscription rather than standalone pay-as-you-go charges.",
  },
  {
    src: "/diagrams/arch-billing.svg",
    title: "Licensing & billing — one Gemini Enterprise subscription covers it all",
    body: "The project holds a Gemini Enterprise license config — per-user/month seats (Search + Assistant tier). Human users consume seats (auto-assigned on first sign-in via the user store), and the app's backend calls run under the same project subscription. Because every Discovery Engine call — faceted search against the data store AND grounded Q&A via the assistant — is made through the GE engine, usage draws on that pooled per-seat plan: no per-query search SKU, no per-token Gemini charges. By default the app avoids the paths that would bill separately: querying the data store directly (standalone Vertex AI Search, SKU 93D6-7280-CF05) and direct Vertex Gemini generateContent calls. One optional add-on is metered on purpose: turning on the cross-encoder Ranking API (--rerank) sharpens result ordering and surfaces per-result relevance scores, at a per-search charge on that same SKU — enabled deliberately here and its spend tracked via the BigQuery billing export (see sql/analytics.sql). Everything else on the bill is ordinary infrastructure — Cloud Run hosting, Cloud Storage, Firestore, BigQuery — hosting costs, not AI fees. You can verify in Cloud Billing by grouping by SKU after a batch of queries.",
  },
  {
    title: "Ranking & relevance — why the scores look the way they do",
    body: "Results are ranked by the Gemini Enterprise engine's native hybrid (semantic + keyword) retrieval. Relevance scores are for relative ordering, not a calibrated 0.5 threshold: strict ranking reserves high scores for near-exact matches, so most genuinely-useful context lands in the lower band — that's expected, not a defect. Use rank order, not an absolute cutoff. (A separate cross-encoder Ranking API can sharpen ordering further but is billed standalone, so it's off by default to keep all traffic under the subscription.)",
  },
  {
    src: "/diagrams/arch-ingest.svg",
    title: "Catalog & document-processing pipeline",
    body: "A Firestore catalog collection is the single on-ramp. An idempotent reconcile job (Cloud Scheduler) loads only the delta into VAIS — staging content to GCS, importing/deleting in the index, seeding the ACL graph, and writing a BigQuery ledger. On import, Vertex AI Search runs its layout parser (text, tables, headings; OCR for scanned PDFs), splits documents into structure-preserving ~500-token chunks, and builds a hybrid semantic + keyword index (with acl_groups filterable). The same job handles the initial bulk load and ongoing incremental updates.",
  },
  {
    src: "/diagrams/arch-aws-sync.svg",
    title: "Syncing with AWS DynamoDB",
    body: "The catalog is the contract boundary. A DynamoDB-Streams → Lambda bridge (or a GCP-side boto3 poller) writes catalog records in the same shape; the reconcile job only ever reads Firestore — so the search app and ingest never depend on AWS credentials.",
  },
  {
    src: "/diagrams/arch-logging.svg",
    title: "Logging, analytics & feedback",
    body: "Every interaction is logged server-side (best-effort, never blocking the request) to BigQuery — searches, AI turns (with latency), feedback votes, and ingestion events — all joinable by a per-search correlation id. That powers tracking and optimization: relevance and zero-result queries, AI attach rate, latency/cost, and ingestion health. Per-result 👍/👎 feedback also feeds VAIS user events (learn-to-rank), so the ranking improves with use. Ready-to-run queries live in sql/analytics.sql.",
  },
  {
    title: "Optional exports — billing & platform logs in BigQuery",
    body: "Two flag-gated Terraform add-ons (off by default; deploy with --billing-export / --logging-export) extend the built-in app analytics with platform-level data. Billing export streams Cloud Billing's per-SKU usage cost into a `billing_export` dataset, so verifying the cost model becomes a SQL query — e.g. confirm no standalone Vertex AI Search SKU (93D6-7280-CF05) or per-token Gemini charges appear, i.e. all AI traffic rides the Gemini Enterprise subscription (one-time Console step to point the billing account at the dataset; Google exposes no API for that). Logging export adds a Cloud Logging sink that streams the Cloud Run service and job logs into date-partitioned tables in `ge_search_app_logs` — raw request latencies, error traces, assist/ingest events — joinable with the app's own ge_search_logs tables for troubleshooting (e.g. tie a slow answer to its request log and ingest state).",
  },
];

/** "How it works" — the architecture diagrams, rendered from /public/diagrams/*.svg. */
export function HowItWorks({ onHome }: { onHome?: () => void }) {
  return (
    <div className="min-h-screen bg-white">
      <header className="sticky top-0 z-30 border-b border-amgen-line bg-white/90 backdrop-blur">
        <div className="mx-auto flex max-w-5xl items-center gap-4 px-4 py-3">
          <Wordmark onLight onHome={onHome} />
          <button
            onClick={onHome}
            className="ml-auto inline-flex items-center gap-1.5 rounded-lg border border-amgen-line px-3 py-1.5 text-sm text-amgen-muted hover:border-amgen-blue hover:text-amgen-blue"
          >
            <ArrowLeft size={15} /> Back to search
          </button>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-4 py-8">
        <h1 className="text-2xl font-extrabold tracking-tight text-amgen-blue">How it works</h1>
        <p className="mt-2 max-w-3xl text-sm text-amgen-muted">
          A custom front-end over Gemini Enterprise / Vertex AI Search, with per-user security
          trimming via an external Firestore permission graph — and a DynamoDB-ready, incremental
          ingestion pipeline.
        </p>

        <div className="mt-8 space-y-10">
          {SECTIONS.map((s) => (
            <section key={s.title}>
              <h2 className="text-lg font-bold text-amgen-ink">{s.title}</h2>
              <p className="mt-1 max-w-3xl text-sm text-amgen-muted">{s.body}</p>
              {s.src && (
                <div className="mt-3 overflow-hidden rounded-2xl border border-amgen-line bg-white shadow-card">
                  <img src={s.src} alt={s.title} className="w-full" />
                </div>
              )}
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
