export interface Persona {
  email: string;
  display_name: string;
  title: string;
  groups: string[];
}

export interface AppConfig {
  dataStoreId: string;
  identitySource: string;
  personas: Persona[];
  facetFields: string[];
}

// per-request AI options chosen in the UI. Answers are always generated by the GE engine
// assistant (no model/engine choice); only the search correlation id flows through.
export interface AiOpts {
  searchId?: string;  // correlates the AI turn back to the originating search
  sessionId?: string; // threads the assistant conversation so follow-ups keep context
}

export interface SearchResult {
  documentId: string;
  title: string;
  sourceUrl?: string;
  gcsUri?: string;
  snippet?: string;
  company?: string;
  department?: string;
  doc_type?: string;
  report_kind?: string;
  research_source?: string;
  research_area?: string;
  venue?: string;
  year?: string;
  publish_date?: string;
  rerankScore?: number; // semantic Ranking API relevance (0-1); shown in demo mode
}

export interface Citation {
  index: number;
  title: string;
  sourceUrl?: string;
  snippet?: string;
}

export interface FacetValue {
  value: string;
  count: number;
}

export interface SearchResponse {
  user: string;
  searchId?: string;
  results: SearchResult[];
  citations: Citation[];
  appliedFilters: Record<string, string | string[]>;
  availableFilters: Record<string, FacetValue[]>;
}

// Provenance shown next to the AI answer. tokensEstimated is derived from answer
// length (~4 chars/token) — the GE assistant doesn't meter tokens (per-seat
// subscription, not per-token billing) and doesn't disclose the underlying model.
export interface AnswerMeta {
  assistant: string;
  model: string;
  tokensEstimated: number;
  latencyMs: number;
}

// AI answer is served separately (opt-in) by /api/answer so search stays fast.
export interface AnswerResponse {
  user: string;
  summary: string;
  citations: Citation[];
  meta?: AnswerMeta;
  sessionId?: string; // assistant session to thread into follow-up Q&A
}
